import { Inter } from "next/font/google";
import "../styles/main.scss";
import NextThemeProvider from "@/context/providers";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "E-comm Store ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextThemeProvider>
          <Toaster
            position="top-center"
            reverseOrder={false}
          />
          {children}
        </NextThemeProvider>
      </body>
    </html>
  );
}
